# Generated by Django 3.0.8 on 2020-07-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now=True, unique=True)),
                ('total_tweets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_positive', models.PositiveIntegerField(blank=True, null=True)),
                ('total_negative', models.PositiveIntegerField(blank=True, null=True)),
                ('total_alarming', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_tweets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_positive', models.PositiveIntegerField(blank=True, null=True)),
                ('total_negative', models.PositiveIntegerField(blank=True, null=True)),
                ('total_alarming', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='main_app.Category')),
            ],
            options={
                'verbose_name_plural': 'sub-categories',
                'ordering': ('category',),
            },
        ),
    ]
