# Generated by Django 3.0.8 on 2020-07-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
