# Generated by Django 3.0.8 on 2020-07-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200722_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_alarming',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_negative',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_positive',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_tweets',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='total_alarming',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='total_negative',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='total_positive',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='total_tweets',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='SubCategoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_tweets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_positive', models.PositiveIntegerField(blank=True, null=True)),
                ('total_negative', models.PositiveIntegerField(blank=True, null=True)),
                ('total_alarming', models.PositiveIntegerField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_details', to='main_app.SubCategory')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_tweets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_positive', models.PositiveIntegerField(blank=True, null=True)),
                ('total_negative', models.PositiveIntegerField(blank=True, null=True)),
                ('total_alarming', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_details', to='main_app.Category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
