# Generated by Django 3.0.8 on 2020-07-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200722_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDetails',
            new_name='CategoryDetail',
        ),
    ]
