# Generated by Django 3.0.8 on 2020-08-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200722_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydetail',
            options={'get_latest_by': 'created', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_ID', models.BigIntegerField(unique=True)),
                ('tweet_date', models.DateTimeField(db_index=True)),
                ('tweet_username', models.CharField(max_length=100)),
                ('tweet_content', models.TextField()),
                ('tweet_URL', models.URLField()),
                ('tweet_sentiment', models.CharField(db_index=True, max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'tweets',
                'ordering': ('-tweet_date',),
            },
        ),
    ]
