# Generated by Django 3.0.8 on 2020-11-01 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200810_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='hasbeenreplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweets',
            name='tweet_day',
            field=models.DateField(db_index=True, default=datetime.date(2020, 11, 1), null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='tweet_week',
            field=models.IntegerField(blank=True, default=201901, null=True),
        ),
    ]
