# Generated by Django 3.0.8 on 2020-11-07 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201101_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet_day',
            field=models.DateField(db_index=True, default=datetime.date(2020, 11, 7), null=True),
        ),
    ]
