# Generated by Django 3.0.8 on 2020-11-20 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201107_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet_day',
            field=models.DateField(db_index=True, default=datetime.date(2020, 11, 20), null=True),
        ),
    ]
